[project]
name = "ensoul"
version = "0.19"
description = "Ensoul is your next CLI agent."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-client-protocol>=0.3.0",
    "aiofiles>=24.1.0",
    "click>=8.2.1",
    "kosong>=0.13.0",
    "loguru>=0.7.3",
    "prompt-toolkit>=3.0.52",
    "pyyaml>=6.0.3",
    "rich>=14.1.0",
    "ripgrepy>=2.2.0",
    "streamingjson>=0.0.5",
    "tenacity>=9.1.2",
]

[dependency-groups]
dev = [
    "inline-snapshot[black]>=0.29.0",
    "pyinstaller>=6.16.0",
    "pyright>=1.1.405",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.0",
]

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["kimi_cli"]

[project.scripts]
kimi = "kimi_cli:main"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]
