[project]
name = "ensoul"
version = "0.8.1"
description = "Ensoul is your next CLI agent."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "kosong>=0.6.0",
    "prompt-toolkit>=3.0.52",
    "pyyaml>=6.0.2",
    "rich>=14.1.0",
    "streamingjson>=0.0.5",
]

[dependency-groups]
dev = ["pyinstaller>=6.16.0", "pytest>=8.4.2", "ruff>=0.12.12"]

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["kimi_cli"]

[project.scripts]
kimi = "kimi_cli:main"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]
