name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          allow-prereleases: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.8.5"

      - name: Cache ripgrep
        uses: actions/cache@v4
        with:
          path: ~/.local/bin
          key: ripgrep-${{ runner.os }}-${{ runner.arch }}-14.1.1
          restore-keys: |
            ripgrep-${{ runner.os }}-${{ runner.arch }}-

      - name: Install ripgrep
        run: |
          mkdir -p "$HOME/.local/bin"
          if [ ! -x "$HOME/.local/bin/rg" ]; then
            if [ "$RUNNER_OS" = "Linux" ]; then
              sudo apt-get update
              sudo apt-get install -y ripgrep
              SRC="/usr/bin/rg"
            elif [ "$RUNNER_OS" = "macOS" ]; then
              brew update || true
              brew install ripgrep || true
              SRC="$(brew --prefix)/bin/rg"
            else
              echo "Unsupported OS: $RUNNER_OS" >&2
              exit 1
            fi
            cp "$SRC" "$HOME/.local/bin/rg"
          fi
          chmod +x "$HOME/.local/bin/rg"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run checks
        run: make check

      - name: Run tests
        run: make test

      - name: Build standalone binary
        run: make build

      - name: Smoke test binary --help
        run: ./dist/kimi --help

      - name: Upload binary artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kimi-${{ matrix.os }}
          path: dist/kimi
          if-no-files-found: error
          retention-days: 7
